FROM balenalib/rpi-debian-python:3.7.3-stretch-build

RUN apt-get update
RUN apt-get install -y redis-tools
RUN apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 swig
RUN useradd -m admin

# pip はこのタイミングでインストールする
ENV REQUIREMENTS_URL https://raw.githubusercontent.com/high-moctane/milbot/master/milbot/requirements.txt
RUN pip install -r $(curl ${REQUIREMENTS_URL})

WORKDIR /home/admin
COPY . .

USER admin
CMD ["python3", "main.py"]