FROM balenalib/rpi-debian-python:3.7.3-stretch-build

RUN apt-get update
RUN apt-get install -y redis-tools
RUN apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 swig
RUN useradd -m admin

WORKDIR /home/admin
COPY . .

RUN pip install -r requirements.txt

ENV HOST_ADDRESS host_address

USER admin
CMD ["python3", "main.py"]