FROM python:3.7.3-stretch

RUN apt-get update && \
    apt-get install -y mecab mecab-ipadic redis-tools && \
    useradd -m admin
USER admin

WORKDIR /home/admin
COPY . .

RUN pip install --user -r requirements.txt

CMD ["python3", "main.py"]